# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'



target 'dscoveryTask' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleSignIn'
 pod 'Firebase/Core', '3.2.1'
 pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  # Pods for dscoveryTask

  target 'dscoveryTask-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dscoveryTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'dscoveryTask-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dscoveryTask-tvOS

  

end
